React: hook up linking multiple files and make sequencing_date a required field
ccmbioinfo/stager pull request #299
Opened 2021-01-06 23:26 UTC by annnag

Closes #281

2021-01-07 14:00 UTC, frewmack requested changes
The issue is not quite closed since the component used for editing a dataset from the Datasets page is not up-to-date. I'd suggest refactoring the FileLinkingCell component used in DataEntryTable so that the popover is a separate reusable component, then use that in the edit component for the Datasets table.

2021-01-07 16:01 UTC, kevinlul reviewed
Add datasets works as expected. I just merged #297, which is the cause of the merge conflicts here

2021-01-08 15:56 UTC, kevinlul requested changes

2021-01-08 15:56 UTC, kevinlul commented on react/src/Datasets/components/DatasetTable.tsx
> +                                    file => ({ title: file, inputValue: file } as Option)
Is the typecast here needed?

2021-01-08 15:56 UTC, kevinlul commented on react/src/components/FileLinkingComponent.tsx
> +                </span>
Same question here

2021-01-11 15:05 UTC, annnag commented on react/src/AddDatasets/components/TableCells.tsx
> +                </span>
To fix this error in the console:`You are providing a disabled button child to the Tooltip component`. This wrapper element also allows the tooltip to be activated when the button is disabled.

2021-01-11 15:47 UTC, kevinlul approved these changes

2021-01-11 22:11 UTC, merged