React: Permission group multiselect in Add Datasets
ccmbioinfo/stager pull request #302
Opened 2021-01-07 21:06 UTC by frewmack

Closes #259. Also changes /api/login to send the user's permission groups on login.

2021-01-07 21:26 UTC, kevinlul requested changes

2021-01-07 21:26 UTC, kevinlul commented on react/src/AddDatasets/components/DataEntryTable.tsx
> +                    disabled={props.allGroups.length <= 1}
When I first sign in I always get an error on this line that `allGroups` is undefined when navigating to add datasets. This is fixed by a hard refresh.

2021-01-07 22:33 UTC, kevinlul requested changes
This works great and I like that the selection is disabled if the user cannot make a meaningful choice.

2021-01-07 22:33 UTC, kevinlul commented on react/src/AddDatasets/index.tsx
> +            setErrorMessage("Cannot submit. You are not part of any permission groups.");
Can a similar message be added for when the user attempts to submit with the field not filled out?

2021-01-08 15:41 UTC, kevinlul requested changes

2021-01-08 15:41 UTC, kevinlul commented on react/src/AddDatasets/index.tsx
> +        }
I think the error condition needs to consider both the filled-out state of the entire form and the dropdown. This worked initially, but when I filled out the table, the submit button was enabled again.

2021-01-08 16:12 UTC, kevinlul approved these changes
LGTM!

2021-01-11 23:11 UTC, annnag requested changes
Looks good to me! Everything works as expected.
One super minor problem: when one dataset is added, the snack bar says `1 datasets...` instead of `1 dataset...`

2021-01-12 16:01 UTC, annnag approved these changes

2021-01-12 16:06 UTC, kevinlul commented
We have a merge conflict because #299 was merged

2021-01-12 16:33 UTC, merged