React: updates to Add Datasets
ccmbioinfo/stager pull request #579
Opened 2021-05-11 18:29 UTC by cklamann

* attach notes to dataset, not participant model in _bulk endpoint
* use defaults from session storage (if they exist) as initial search state
* create fresh defaults on form submission
* make notes field free text (though still technically autocomplete)
* update value of non-enum fields on blur
* add empty string default options where appropriate to suppress console warnings

2021-05-11 20:39 UTC, kevinlul commented
Does this address the problem with types disappearing from the autocomplete?

2021-05-12 20:25 UTC, kevinlul requested changes

2021-05-12 20:25 UTC, kevinlul commented on react/src/AddDatasets/components/TableCells.tsx
> +    const getIsFreeSolo = () => props.column.field === "notes";
```suggestion
    const isFreeSolo = () => props.column.field === "notes";
```

2021-05-12 20:47 UTC, kevinlul approved these changes
LGTM!

2021-05-13 17:23 UTC, frewmack approved these changes
LGTM!

2021-05-13 20:37 UTC, merged