Jenny/add sequencing id to dataset table
ccmbioinfo/stager pull request #822
Opened 2021-09-17 17:50 UTC by jennyziyi-xu

Added a column `sequencing_id` to the dataset table. The column can be sorted and filtered. Added test cases in test_datasets.py. Added field `sequencing_id` to the global test cases in conftest.py. 

Comment: Currently, only 4 datasets for pytest are documented in flask.md, should we update flask.md? There are 5 datasets in conftest.py.

2021-09-17 17:53 UTC, hannahle commented
> Comment: Currently, only 4 datasets for pytest are documented in flask.md, should we update flask.md? There are 5 datasets in conftest.py.

This is because I updated conftest.py recently. I will update the flask.md. Thanks for pointing that out!

2021-09-17 21:34 UTC, kevinlul requested changes
Please enter a pull request title instead of the automatically-generated one!

2021-09-17 21:34 UTC, kevinlul commented on flask/app/datasets.py
> +        order = models.Dataset.sequencing_id
This is a field of the dataset table, so it is already handled by the prior elif by being included in the list and does not need to be explicitly done here.

2021-09-17 21:34 UTC, kevinlul commented on flask/tests/conftest.py
> +        sequencing_id=5,
This column is a string, so it shouldn't be an int here

2021-09-20 17:38 UTC, kevinlul commented
> Please enter a pull request title instead of the automatically-generated one!

2021-09-20 18:16 UTC, jennyziyi-xu commented
> Please enter a pull request title instead of the automatically-generated one!

Done. Sorry, was a bit confused.

2021-09-20 19:50 UTC, kevinlul approved these changes
LGTM!

2021-09-21 13:02 UTC, merged