SQLAlchemy: Upgrade to version 1.4.27
ccmbioinfo/stager pull request #959
Opened 2021-11-29 18:59 UTC by jennyziyi-xu

Before, we access a subquery's column directly as `subquery.column_name`. By upgrading to version 1.4.27, the column can no longer be found this way and will lead to errors. I have modified it to `subquery.c.column_name`.

I have added `select` construct explicitly in certain places to suppress warning messages. 

There is one warning message remaining and I haven't found the solution yet. I don't see any Cartesian Product as is indicated by the warning message. 
![SQL warning](https://user-images.githubusercontent.com/56279639/143926482-2353e190-8c91-42f4-8153-73cc8142285f.png)

2021-11-30 21:13 UTC, delvinso commented
After debugging, the warning can be confirmed to be i) from L390 in `variants.py` and ii) only for the 'gene' search type. When the search type is 'gene', ie. using the ENSG ID to filter the variants, there is a filter placed on `gene.ensembl_id`. It looks like the problem is from the lack of an explicit join between the `Variant` and `Gene` tables, yielding the following SQL statement. 

```
SELECT count(DISTINCT variant.variant_id) AS count_1 
FROM variant, gene 
WHERE gene.ensembl_id IN (__[POSTCOMPILE_ensembl_id_1])

# apparently the comma in the FROM statement results in a cartesian product, hence the warning?: https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#built-in-from-linting-will-warn-for-any-potential-cartesian-products-in-a-select-statement
# thanks to Jenny for the link
```
This can be fixed by using a join between`Variant` and `Gene` (because of the search strategy we employ, there is no explicit relationship between these two tables). This results in the following statement:

```
SELECT count(DISTINCT variant.variant_id) AS count_1 
FROM gene JOIN variant ON gene.chromosome = variant.chromosome AND gene.start <= variant.position AND variant.position <= gene."end" 
WHERE gene.ensembl_id IN (__[POSTCOMPILE_ensembl_id_1])

```

2021-11-30 21:30 UTC, jennyziyi-xu commented
Nice! It was confusing which line is causing the problem. I was focusing on the wrong place.

2021-12-01 15:54 UTC, cklamann requested changes
Delvin noticed that with this upgrade, queries will fail when they try to select records with a `null` `discriminator` column. Since most `dataset.discriminator` columns are `null`, we will need to update them with the appropriate values before this can be merged and probably make the column itself non-nullable. Changelog [here](https://github.com/sqlalchemy/sqlalchemy/blob/main/doc/build/changelog/changelog_14.rst). Relevant excerpt:
```
.. change::
        :tags: bug, orm
        :tickets: 4836

        An exception is now raised if the ORM loads a row for a polymorphic
        instance that has a primary key but the discriminator column is NULL, as
        discriminator columns should not be null.

2021-12-01 15:54 UTC, cklamann commented on flask/app/analyses.py
> +    app.logger.info(results)
Stray logging statement?

2021-12-09 20:18 UTC, delvinso approved these changes
LGTM - works as expected!

2021-12-09 20:21 UTC, cklamann approved these changes

2021-12-09 20:28 UTC, merged