Flask: add input validation using marshmallow
ccmbioinfo/stager pull request #974
Opened 2021-12-03 20:47 UTC by delvinso

closes #218 

- adds `flask-marshmallow` and `marshmallow-sqlalchemy` to requirements 
- schemas are stored in `schemas.py`
- for a first pass, schemas have been automagically constructed for `Dataset` and `Analysis` using the sqlalchemy models with custom validation depending on the endpoint. I tried using a decorator to automatically construct a schema when the models are created (the schema would be an attribute) but was getting some errors related to relationship definitions. Regardless it may not be the best idea anyways to use a decorator to construct the schema given that we do have quite a bit of custom endpoint logic (and therefore custom validation).
- as an added bonus enum validation seems to be taken care of since the schemas are constructed using the models via `SQLAlchemyAutoSchema` 

- All errors are now returned at once

```
curl -X POST localhost:5000/api/analyses \
  -H 'Content-Type: application/json' \
  -d '{"datasets": ["haha"], "pipeline_id": 1, "priority": "NOPE"}'
{
  "error": "{'datasets': {0: ['Not a valid integer.']}, 'priority': ['Must be one of: Clinical, Research.']}"
}
```

2021-12-03 22:11 UTC, kevinlul commented
Neat, this isn't as complicated as I expected!

2021-12-09 16:41 UTC, jennyziyi-xu requested changes
A minor request: `validate_enums` doesn't need to be imported anymore in most python files. 

Is there a need to use marshmallow for input validation in the `bulk` POST endpoint?

2021-12-09 18:10 UTC, jennyziyi-xu requested changes

2021-12-09 18:10 UTC, jennyziyi-xu commented on flask/app/schemas.py
> +from marshmallow import fields, Schema
```suggestion
from marshmallow import fields
```

2021-12-09 19:00 UTC, delvinso commented
> A minor request: `validate_enums` doesn't need to be imported anymore in most python files.
> 
> Is there a need to use marshmallow for input validation in the `bulk` POST endpoint?

I think the decision was to split the input validation into 2 PRs since the `_bulk`, `users` and `groups` are more complicated due to the custom validation we use.

2021-12-09 19:22 UTC, jennyziyi-xu approved these changes

2021-12-10 14:36 UTC, merged